#------------------------------------------------------------------------------

SOURCE=AssemblerTranslator.cpp
MYPROGRAM=AssemblerTranslatorExe
CC= g++ -Wall -std=c++11 -fexceptions

#------------------------------------------------------------------------------

all: $(MYPROGRAM)


$(MYPROGRAM): $(SOURCE)
	$(CC) $(SOURCE) -o$(MYPROGRAM)
clean:
	rm -f $(MYPROGRAM)
